stages:
  - build
  - deploy
  
build_images:
  stage: build
  image: docker:20.10.16  

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t bombonatto/projeto_pipeline_k8s:1.0 app/.
    - docker push bombonatto/projeto_pipeline_k8s:1.0

deploy:
  stage: deploy

  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./projeto_pipeline_k8s/ && sudo git clone https://gitlab.com/bombonatto/projeto_pipeline_k8s.git && cd projeto_pipeline_k8s && sudo chmod +x ./script_install.sh && ./script_install.sh"


    